# Text data representations

## Example 'real' data: SIPA description, #migrantcrisis tweets

SIPA text is taken from the Wikipedia entry about SIPA, https://en.wikipedia.org/wiki/School_of_International_and_Public_Affairs,_Columbia_University.

Migrantcrisis tweets were read from the twitter search API (see notebook 3.2 Social Media Data), using hashtag #migrantcrisis, on 9th March 2016.

In [1]:
fsipa = open('example_data/sipatext.txt', 'r')
sipatext = fsipa.read()
fsipa.close()
print(sipatext)

The School of International and Public Affairs at Columbia University (also known at SIPA) is a public policy and international affairs school and one of Columbia's graduate and professional schools.

Located on Columbia's Morningside Heights campus in the Borough ofManhattan, in New York City, the school has more than 19,000 alumni in more than 150 countries. SIPA's alumni include former heads of state, business leaders, journalists, diplomats, and elected representatives. Many graduates reach the upper echelons of central banks and treasuries, others go to energy companies, non-for-profits and social enterprises.[1] Half of SIPAâ€™s nearly 1,400 students are international, coming from over 100 countries. SIPA has more than 70 full-time faculty and more than 200 adjunct professors, including the world's leading scholars on international relations.

The school offers two traditional two-year master's degrees (Master of Public Administration or Master of International Affairs), an Executive MPA, an Environmental Science and Policy program, an Economic Policy Management program, a Development Practice degree, and a Ph.D. program in Sustainable Development. SIPA also offers a number of dual-degree programs with other Columbia University schools and, through the Global Public Policy Network (GPPN), offers international dual degree programs with the London School of Economics and Political Science, the Institut d'Ã‰tudes Politiques de Paris(Sciences Po), the Hertie School of Governance in Berlin, the University of Tokyo and the Lee Kuan Yew School of Public Policy at the National University of Singapore.[2]

In [2]:
import json
import pandas as pd
from pandas.io.json import json_normalize

ftweets = open('example_data/migrantcrisis_tweets.json', 'r')
tweetdata = json.load(ftweets)
ftweets.close()
# print('One tweet: {}'.format(tweetdata['statuses'][0]))

tweetframe = json_normalize(tweetdata['statuses'])
print('Dataframe columns: ')
for c in tweetframe.columns:
    print('{}, '.format(c), end=' ')
print('\n')
tweetframe[['user.screen_name', 'text', 'entities.hashtags']]

Dataframe columns:
contributors,  coordinates,  created_at,  entities.hashtags,  entities.media,  entities.symbols,  entities.urls,  entities.user_mentions,  favorite_count,  favorited,  geo,  id,  id_str,  in_reply_to_screen_name,  in_reply_to_status_id,  in_reply_to_status_id_str,  in_reply_to_user_id,  in_reply_to_user_id_str,  is_quote_status,  lang,  metadata.iso_language_code,  metadata.result_type,  place,  possibly_sensitive,  retweet_count,  retweeted,  retweeted_status.contributors,  retweeted_status.coordinates,  retweeted_status.created_at,  retweeted_status.entities.hashtags,  retweeted_status.entities.media,  retweeted_status.entities.symbols,  retweeted_status.entities.urls,  retweeted_status.entities.user_mentions,  retweeted_status.favorite_count,  retweeted_status.favorited,  retweeted_status.geo,  retweeted_status.id,  retweeted_status.id_str,  retweeted_status.in_reply_to_screen_name,  retweeted_status.in_reply_to_status_id,  retweeted_status.in_reply_to_status_id_str,  retweeted_status.in_reply_to_user_id,  retweeted_status.in_reply_to_user_id_str,  retweeted_status.is_quote_status,  retweeted_status.lang,  retweeted_status.metadata.iso_language_code,  retweeted_status.metadata.result_type,  retweeted_status.place,  retweeted_status.possibly_sensitive,  retweeted_status.retweet_count,  retweeted_status.retweeted,  retweeted_status.source,  retweeted_status.text,  retweeted_status.truncated,  retweeted_status.user.contributors_enabled,  retweeted_status.user.created_at,  retweeted_status.user.default_profile,  retweeted_status.user.default_profile_image,  retweeted_status.user.description,  retweeted_status.user.entities.description.urls,  retweeted_status.user.entities.url.urls,  retweeted_status.user.favourites_count,  retweeted_status.user.follow_request_sent,  retweeted_status.user.followers_count,  retweeted_status.user.following,  retweeted_status.user.friends_count,  retweeted_status.user.geo_enabled,  retweeted_status.user.has_extended_profile,  retweeted_status.user.id,  retweeted_status.user.id_str,  retweeted_status.user.is_translation_enabled,  retweeted_status.user.is_translator,  retweeted_status.user.lang,  retweeted_status.user.listed_count,  retweeted_status.user.location,  retweeted_status.user.name,  retweeted_status.user.notifications,  retweeted_status.user.profile_background_color,  retweeted_status.user.profile_background_image_url,  retweeted_status.user.profile_background_image_url_https,  retweeted_status.user.profile_background_tile,  retweeted_status.user.profile_banner_url,  retweeted_status.user.profile_image_url,  retweeted_status.user.profile_image_url_https,  retweeted_status.user.profile_link_color,  retweeted_status.user.profile_sidebar_border_color,  retweeted_status.user.profile_sidebar_fill_color,  retweeted_status.user.profile_text_color,  retweeted_status.user.profile_use_background_image,  retweeted_status.user.protected,  retweeted_status.user.screen_name,  retweeted_status.user.statuses_count,  retweeted_status.user.time_zone,  retweeted_status.user.url,  retweeted_status.user.utc_offset,  retweeted_status.user.verified,  source,  text,  truncated,  user.contributors_enabled,  user.created_at,  user.default_profile,  user.default_profile_image,  user.description,  user.entities.description.urls,  user.entities.url.urls,  user.favourites_count,  user.follow_request_sent,  user.followers_count,  user.following,  user.friends_count,  user.geo_enabled,  user.has_extended_profile,  user.id,  user.id_str,  user.is_translation_enabled,  user.is_translator,  user.lang,  user.listed_count,  user.location,  user.name,  user.notifications,  user.profile_background_color,  user.profile_background_image_url,  user.profile_background_image_url_https,  user.profile_background_tile,  user.profile_banner_url,  user.profile_image_url,  user.profile_image_url_https,  user.profile_link_color,  user.profile_sidebar_border_color,  user.profile_sidebar_fill_color,  user.profile_text_color,  user.profile_use_background_image,  user.protected,  user.screen_name,  user.statuses_count,  user.time_zone,  user.url,  user.utc_offset,  user.verified,

,user.screen_name,text,entities.hashtags
0,politic_ALL,Stirile zilei - 9 martie: https://t.co/R3n6Vr8...,"[{'text': 'BreakingNews', 'indices': [50, 63]}..."
1,RachCoffey,https://t.co/I09bHPUEyM via @youtube @guardian...,"[{'text': 'migrantcrisis', 'indices': [47, 61]}]"
2,sassysassyred,RT @ECentauri: GERMAN GOVT. PROMOTES INTERRACI...,"[{'text': 'migrantcrisis', 'indices': [77, 91]..."
3,BorisNevermore,RT @vladokrstevski: #NeoCommies\n#UDBA\n#Soros...,"[{'text': 'NeoCommies', 'indices': [20, 31]}, ..."
4,mlpostier,RT @ECentauri: 'I GOT A SOLUTION TO #migrantcr...,"[{'text': 'migrantcrisis', 'indices': [36, 50]..."
5,alexfenyvesi,"#Migrants - Feeling Unwanted In Germany, Some ...","[{'text': 'Migrants', 'indices': [0, 9]}, {'te..."
6,simbeeee,"RT @INTHENOWRT: This drone captures some 14,00...","[{'text': 'refugees', 'indices': [48, 57]}, {'..."
7,hattieeds14,People who moan about the migrant crisis.... ðŸ–•...,"[{'text': 'migrantcrisis', 'indices': [48, 62]..."
8,ritapreach,RT @London_360: .@RitaOra delivers a personal ...,"[{'text': 'migrantcrisis', 'indices': [80, 94]..."
9,SolerBatalla,"RT @INTHENOWRT: This drone captures some 14,00...","[{'text': 'refugees', 'indices': [48, 57]}, {'..."
10,ElementaryForce,@lksriv but on the otherhand ...\nhttps://t.co...,"[{'text': 'migrantcrisis', 'indices': [57, 71]..."
11,ElementaryForce,@zoharfisher @TheEconomist wonder if she think...,"[{'text': 'migrantcrisis', 'indices': [62, 76]..."
12,WesternHeff,RT @newint: #PhotoGallery | #MigrantCrisis: As...,"[{'text': 'PhotoGallery', 'indices': [12, 25]}..."
13,fanaddikt,Germany/Japan should both accept ALL of the wo...,"[{'text': 'RefugeeCrisis', 'indices': [102, 11..."
14,ElementaryForce,RT @petersthoughts: The Death of the Most Gene...,"[{'text': 'migrantcrisis', 'indices': [91, 105..."

## Using the raw data

Sometime you'll want to use the raw data itself as input to algorithms.  Examples of this include things like Twitter hashtags or user names, which are short and (hopefully) consistent.

## Using Bags of Words

In [3]:
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

count_vect = CountVectorizer()
word_counts = count_vect.fit_transform([sipatext])
print('{}'.format(word_counts))
print('{}'.format(count_vect.vocabulary_))

  (0, 120)	13
  (0, 109)	7
  (0, 83)	13
  (0, 61)	6
  (0, 13)	13
  (0, 104)	5
  (0, 9)	3
  (0, 15)	3
  (0, 23)	4
  (0, 128)	4
  (0, 10)	2
  (0, 64)	1
  (0, 114)	5
  (0, 62)	1
  (0, 95)	5
  (0, 87)	1
  (0, 50)	1
  (0, 99)	1
  (0, 110)	2
  (0, 69)	1
  (0, 86)	2
  (0, 75)	1
  (0, 55)	1
  (0, 20)	1
  (0, 57)	5
  :	:
  (0, 130)	2
  (0, 89)	1
  (0, 121)	1
  (0, 46)	1
  (0, 79)	1
  (0, 49)	1
  (0, 70)	1
  (0, 35)	1
  (0, 96)	1
  (0, 60)	1
  (0, 135)	1
  (0, 97)	1
  (0, 27)	1
  (0, 92)	1
  (0, 112)	1
  (0, 94)	1
  (0, 56)	1
  (0, 48)	1
  (0, 17)	1
  (0, 124)	1
  (0, 68)	1
  (0, 65)	1
  (0, 133)	1
  (0, 77)	1
  (0, 113)	1
{'lee': 68, 'berlin': 17, 'international': 61, 'central': 21, 'representatives': 107, 'city': 22, 'in': 57, 'administration': 8, 'sipa': 114, 'ofmanhattan': 85, 'practice': 98, 'to': 123, 'university': 128, 'include': 58, 'mpa': 76, 'de': 27, 'politiques': 97, 'and': 13, 'enterprises': 38, 'policy': 95, 'located': 69, 'of': 83, 'public': 104, 'the': 120, 'known': 64, 'upper': 129, 'than': 119, 'other': 89, 'coming': 24, 'professional': 99, '19': 3, 'more': 74, 'business': 19, 'or': 88, 'institut': 60, 'global': 46, 'scholars': 108, 'from': 44, 'faculty': 41, 'graduate': 50, 'social': 115, 'on': 86, 'morningside': 75, 'paris': 92, 'sciences': 112, 'offers': 84, '400': 5, 'gppn': 49, 'ph': 93, 'dual': 32, 'including': 59, 'has': 53, 'at': 15, 'master': 73, 'many': 72, 'Ã©tudes': 135, 'also': 10, 'affairs': 9, 'leading': 67, 'half': 52, 'for': 42, 'economic': 34, 'new': 80, 'york': 134, 'management': 71, 'school': 109, 'treasuries': 126, 'companies': 25, 'development': 30, 'programs': 103, 'columbia': 23, 'tokyo': 124, 'number': 82, 'degree': 28, 'relations': 106, 'world': 131, 'singapore': 113, 'national': 77, 'elected': 36, 'alumni': 11, 'environmental': 39, 'nearly': 78, 'banks': 16, 'program': 102, 'through': 121, 'non': 81, 'others': 90, 'with': 130, 'yew': 133, 'diplomats': 31, 'time': 122, 'former': 43, 'profits': 101, 'graduates': 51, '70': 6, 'countries': 26, 'full': 45, 'kuan': 65, 'over': 91, '100': 1, 'an': 12, 'hertie': 56, 'adjunct': 7, 'professors': 100, 'traditional': 125, 'echelons': 33, 'executive': 40, 'network': 79, 'journalists': 63, '150': 2, 'energy': 37, 'heights': 55, '000': 0, 'go': 47, 'economics': 35, 'campus': 20, 'sustainable': 118, 'heads': 54, 'degrees': 29, 'schools': 110, 'governance': 48, 'is': 62, 'borough': 18, 'london': 70, 'one': 87, 'reach': 105, 'state': 116, '200': 4, 'are': 14, 'po': 94, 'students': 117, 'leaders': 66, 'science': 111, 'year': 132, 'two': 127, 'political': 96}

Let's have a more civilised look at that word count list, by turning it into a Pandas dataframe, sorted by count...

In [4]:
df = pd.DataFrame(word_counts.A, columns=count_vect.get_feature_names()).transpose()
df.columns = ['count']
df.sort_values(by='count', ascending=False)

               count
and               13
the               13
of                13
school             7
international      6
policy             5
public             5
in                 5
sipa               5
columbia           4
than               4
more               4
university         4
degree             3
program            3
at                 3
master             3
affairs            3
offers             3
an                 3
alumni             2
programs           2
has                2
schools            2
science            2
dual               2
with               2
development        2
also               2
two                2
...              ...
faculty            1
many               1
include            1
management         1
london             1
located            1
100                1
leading            1
leaders            1
kuan               1
known              1
journalists        1
is                 1
institut           1
including          1
hertie             1
for                1
heights            1
heads              1
half               1
graduates          1
graduate           1
gppn               1
governance         1
go                 1
global             1
full               1
from               1
former             1
Ã©tudes             1

[136 rows x 1 columns]

## N-grams

In [5]:
count_vectn = CountVectorizer(ngram_range =(2, 2))
word_countsn = count_vectn.fit_transform([sipatext])

df_n = pd.DataFrame(word_countsn.A, columns=count_vectn.get_feature_names()).transpose()
df_n.columns = ['count']
df_n.sort_values(by='count', ascending=False)

                         count
more than                    4
school of                    4
the school                   3
public policy                3
dual degree                  2
of public                    2
international affairs        2
columbia university          2
countries sipa               2
of international             2
degree programs              2
programs with                2
has more                     2
master of                    2
university of                2
politiques de                1
policy management            1
policy at                    1
policy network               1
policy program               1
political science            1
program an                   1
practice degree              1
professional schools         1
professors including         1
profits and                  1
po the                       1
program development          1
program in                   1
public administration        1
...                        ...
master degrees               1
100 countries                1
morningside heights          1
in sustainable               1
in more                      1
echelons of                  1
from over                    1
economic policy              1
economics and                1
elected representatives      1
energy companies             1
enterprises half             1
environmental science        1
executive mpa                1
faculty and                  1
for profits                  1
former heads                 1
full time                    1
in berlin                    1
global public                1
go to                        1
governance in                1
gppn offers                  1
graduate and                 1
graduates reach              1
half of                      1
heads of                     1
heights campus               1
hertie school                1
Ã©tudes politiques            1

[215 rows x 1 columns]

### Stopwords

In [6]:
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

count_vect2 = CountVectorizer(stop_words='english')
word_counts2 = count_vect2.fit_transform([sipatext])

df2 = pd.DataFrame(word_counts2.A, columns=count_vect2.get_feature_names()).transpose()
df2.columns = ['count']
df2.sort_values(by='count', ascending=False)

               count
school             7
international      6
public             5
policy             5
sipa               5
university         4
columbia           4
program            3
degree             3
affairs            3
master             3
offers             3
programs           2
schools            2
dual               2
science            2
development        2
countries          2
alumni             2
profits            1
nearly             1
mpa                1
professors         1
professional       1
practice           1
politiques         1
number             1
network            1
ofmanhattan        1
paris              1
...              ...
400                1
200                1
19                 1
150                1
elected            1
enterprises        1
london             1
environmental      1
located            1
lee                1
100                1
leaders            1
kuan               1
known              1
journalists        1
institut           1
including          1
include            1
hertie             1
heights            1
heads              1
half               1
graduates          1
graduate           1
gppn               1
governance         1
global             1
faculty            1
executive          1
Ã©tudes             1

[107 rows x 1 columns]

## Using Term frequencies

In [7]:
from sklearn.feature_extraction.text import TfidfTransformer

tf_transformer = TfidfTransformer(use_idf=False)
tf_features = tf_transformer.fit_transform(word_counts2)
print('{}'.format(tf_features))

  (0, 86)	0.372572406789
  (0, 48)	0.319347777247
  (0, 81)	0.266123147706
  (0, 9)	0.159673888624
  (0, 18)	0.212898518165
  (0, 100)	0.212898518165
  (0, 50)	0.0532246295412
  (0, 91)	0.266123147706
  (0, 72)	0.266123147706
  (0, 39)	0.0532246295412
  (0, 76)	0.0532246295412
  (0, 87)	0.106449259082
  (0, 55)	0.0532246295412
  (0, 59)	0.0532246295412
  (0, 43)	0.0532246295412
  (0, 15)	0.0532246295412
  (0, 13)	0.0532246295412
  (0, 68)	0.0532246295412
  (0, 64)	0.0532246295412
  (0, 105)	0.0532246295412
  (0, 17)	0.0532246295412
  (0, 3)	0.0532246295412
  (0, 0)	0.0532246295412
  (0, 10)	0.106449259082
  (0, 2)	0.0532246295412
  :	:
  (0, 95)	0.0532246295412
  (0, 66)	0.0532246295412
  (0, 26)	0.106449259082
  (0, 80)	0.106449259082
  (0, 36)	0.0532246295412
  (0, 63)	0.0532246295412
  (0, 38)	0.0532246295412
  (0, 56)	0.0532246295412
  (0, 29)	0.0532246295412
  (0, 73)	0.0532246295412
  (0, 47)	0.0532246295412
  (0, 106)	0.0532246295412
  (0, 74)	0.0532246295412
  (0, 69)	0.0532246295412
  (0, 89)	0.0532246295412
  (0, 71)	0.0532246295412
  (0, 44)	0.0532246295412
  (0, 37)	0.0532246295412
  (0, 12)	0.0532246295412
  (0, 97)	0.0532246295412
  (0, 54)	0.0532246295412
  (0, 51)	0.0532246295412
  (0, 104)	0.0532246295412
  (0, 61)	0.0532246295412
  (0, 90)	0.0532246295412

In [8]:
tfidf_transformer = TfidfTransformer(use_idf=True)
tfidf_features = tfidf_transformer.fit_transform(word_counts2)
print('{}'.format(tfidf_features))

  (0, 90)	0.0532246295412
  (0, 61)	0.0532246295412
  (0, 104)	0.0532246295412
  (0, 51)	0.0532246295412
  (0, 54)	0.0532246295412
  (0, 97)	0.0532246295412
  (0, 12)	0.0532246295412
  (0, 37)	0.0532246295412
  (0, 44)	0.0532246295412
  (0, 71)	0.0532246295412
  (0, 89)	0.0532246295412
  (0, 69)	0.0532246295412
  (0, 74)	0.0532246295412
  (0, 106)	0.0532246295412
  (0, 47)	0.0532246295412
  (0, 73)	0.0532246295412
  (0, 29)	0.0532246295412
  (0, 56)	0.0532246295412
  (0, 38)	0.0532246295412
  (0, 63)	0.0532246295412
  (0, 36)	0.0532246295412
  (0, 80)	0.106449259082
  (0, 26)	0.106449259082
  (0, 66)	0.0532246295412
  (0, 95)	0.0532246295412
  :	:
  (0, 2)	0.0532246295412
  (0, 10)	0.106449259082
  (0, 0)	0.0532246295412
  (0, 3)	0.0532246295412
  (0, 17)	0.0532246295412
  (0, 105)	0.0532246295412
  (0, 64)	0.0532246295412
  (0, 68)	0.0532246295412
  (0, 13)	0.0532246295412
  (0, 15)	0.0532246295412
  (0, 43)	0.0532246295412
  (0, 59)	0.0532246295412
  (0, 55)	0.0532246295412
  (0, 87)	0.106449259082
  (0, 76)	0.0532246295412
  (0, 39)	0.0532246295412
  (0, 72)	0.266123147706
  (0, 91)	0.266123147706
  (0, 50)	0.0532246295412
  (0, 100)	0.212898518165
  (0, 18)	0.212898518165
  (0, 9)	0.159673888624
  (0, 81)	0.266123147706
  (0, 48)	0.319347777247
  (0, 86)	0.372572406789

## Grammar-sensitive representations

### The NLTK library

WARNINGS: 

* You will have to 'conda install nltk' before you can run the cells below
* And even when you ahve the NLTK library, you won't be able to run the cells below without the NLTK corpora. 

Run the cell below just once.  
* When you run nltk.download(), a popup window will appear. 
* Click on the "models" tab, then "punkt" then the "download" button

If you want more, try clicking on "book" then "download".  If you ever wanted to have the whole of Basque grammar, then click around the tabs in this popup window: this is the place to get it!

In [9]:
import nltk
# nltk.download() #Uncomment this before running the cell

### Word stemming

Some of the words above are plurals, or heavily related to each other.  Word stemming removes all the word endings etc. to leave just the 'root' of each word.

In [10]:
from nltk import word_tokenize          
from nltk.stem.porter import PorterStemmer

#######
# based on http://www.cs.duke.edu/courses/spring14/compsci290/assignments/lab02.html
stemmer = PorterStemmer()
def stem_tokens(tokens, stemmer):
    stemmed = []
    for item in tokens:
        stemmed.append(stemmer.stem(item))
    return stemmed

def tokenize(text):
    tokens = word_tokenize(text)
    stems = stem_tokens(tokens, stemmer)
    return stems
######## 

count_vect3 = CountVectorizer(tokenizer=tokenize, stop_words='english') 
word_counts3 = count_vect3.fit_transform([sipatext])
#print('{}'.format(word_counts3))
#print('{}'.format(count_vect3.vocabulary_))

df3 = pd.DataFrame(word_counts3.A, columns=count_vect3.get_feature_names()).transpose()
df3.columns = ['count']
df3.sort_values(by='count', ascending=False)

             count
,               20
school           9
.                8
intern           6
's               5
polici           5
public           5
program          5
columbia         4
sipa             4
univers          4
(                4
)                4
scienc           3
offer            3
affair           3
degre            3
master           3
ha               2
includ           2
econom           2
countri          2
graduat          2
develop          2
[                2
alumni           2
]                2
singapor         1
two-year         1
tradit           1
...            ...
2                1
19,000           1
150              1
100              1
1,400            1
1                1
diplomat         1
dual             1
dual-degre       1
echelon          1
leader           1
lead             1
kuan             1
known            1
journalist       1
herti            1
height           1
head             1
half             1
gppn             1
govern           1
global           1
full-tim         1
faculti          1
execut           1
environment      1
enterpris        1
energi           1
elect            1
york             1

[111 rows x 1 columns]